//AUTHENTICATION TYPES
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const AUTH_ERROR = 'AUTH_ERROR';
export const CLEAR_USER_PROFILE = 'CLEAR_USER_PROFILE';
export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGGING_IN = 'LOGGING_IN';
//MESSAGE TYPES
export const SENDING_MSG = 'SENDING_MSG';
export const SENDING_MSG_FAIL = 'SENDING_MSG_FAIL';

export const SUCCESS = 'SUCCESSS';
